version: "3"

services:
  #  myredis:
  #    build:
  #      context: redis/
  #      dockerfile: redis.dockerfile
  #    container_name: vergil-redis
  #    ports:
  #      - 6379:6379
  #    restart: always
  myredisstack:
    build:
      context: redis-stack/
      dockerfile: redis-stack.dockerfile
    container_name: vergil-redis-stack
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  mypostgres:
    image: postgres:16.0-alpine3.18
    container_name: vergil-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 921115
      POSTGRES_USER: postgres
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    volumes:
      - /mnt/data/vergil/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  myrabbitmq:
    image: rabbitmq:3.12.4-management-alpine
    container_name: vergil-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=921115
      - RABBITMQ_DEFAULT_USER=vergil
    restart: always
#  mymysql:
#    image: mysql:8.0.33
#    container_name: vergil-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 921115 #root管理员用户密码
#      MYSQL_USER: vergil   #创建test用户
#      MYSQL_PASSWORD: 921115  #设置test用户的密码
#    volumes:
#      #mysql数据库挂载到host物理机目录
#      - /mnt/data/vergil/mysql/db:/var/lib/mysql
#      #容器的配置目录挂载到host物理机目录
#      - /mnt/data/vergil/mysql/config:/etc/mysql/conf.d
#    ports:
#      - 3306:3306
#    restart: always
#  myelasticsearch:
#    image: elasticsearch:8.6.1
#    container_name: myelasticsearch
#    networks:
#      - ek-net
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      - "discovery.type=single-node"
#      - xpack.security.enabled=false  #没这玩意kibana就是跑不起来
#    volumes:
#      - /root/es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - /root/es/data:/usr/share/elasticsearch/data #数据文件挂载
#  mykibana:
#    depends_on:
#      - myelasticsearch
#    image: kibana:8.6.1
#    container_name: mykibana
#    networks:
#      - ek-net
#    environment:
#      - ELASTICSEARCH_HOSTS=http://myelasticsearch:9200
#      - I18N_LOCALE="zh-CN"
#    ports:
#      - 5601:5601
#networks:
#  ek-net:
#    driver: bridge
#  mynacos:
#    image: nacos/nacos-server:v2.2.3-slim
#    container_name: mynacos
#    ports:
#      - 8848:8848
#      - 9848:9848
#    environment:
#      - NACOS_AUTH_IDENTITY_KEY=123456
#      - NACOS_AUTH_IDENTITY_VALUE=123456
#      - NACOS_AUTH_TOKEN=MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5
#      - MODE=standalone
#  minio:
#    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
#    privileged: true
#    container_name: myminio
#    ports:
#      - 9000:9000
#      - 9001:9001
#    command: minio server /data --console-address ":9001"
#    environment:
#      - MINIO_ROOT_USER=vergil
#      - MINIO_ROOT_PASSWORD=19921115
#    volumes:
#      - /mnt/data/vergil/minio:/data
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
#      interval: 30s
#      timeout: 20s
#      retries: 3

#  etcd:
#    container_name: milvus-etcd
#    image: quay.io/coreos/etcd:v3.5.5
#    environment:
#      - ETCD_AUTO_COMPACTION_MODE=revision
#      - ETCD_AUTO_COMPACTION_RETENTION=1000
#      - ETCD_QUOTA_BACKEND_BYTES=4294967296
#      - ETCD_SNAPSHOT_COUNT=50000
#    volumes:
#      - /mnt/data/vergil/etcd:/etcd
#    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

#  milvus:
#    build:
#      context: milvus/
#      dockerfile: milvus.dockerfile
##    image: milvusdb/milvus:v2.2.10
#    container_name: milvus-standalone
#    command: ["milvus", "run", "standalone"]
#    environment:
#      ETCD_ENDPOINTS: etcd:2379
#      MINIO_ADDRESS: minio:9000
#    volumes:
#      - /mnt/data/vergil/milvus:/var/lib/milvus
#    ports:
#      - "19530:19530"
#      - "9091:9091"
#    depends_on:
#      - "minio"
#      - "etcd"
#
#
#  attu:
#    container_name: attu
#    image: zilliz/attu:v2.2.3
#    environment:
#      MILVUS_URL: milvus-standalone:19530
#    ports:
#      - "3000:3000"
#    depends_on:
#      - "milvus"
