version: '3.8'

networks:
  #给监控用的，node_exporter什么的不暴露外网
  monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  elastic:
    driver: bridge


services:

  myredis:
    build:
      context: redis/
      dockerfile: redis.dockerfile
    container_name: vergil-redis
    hostname: vergil-redis
    volumes:
      - /mnt/data/vergil/redis:/data
    ports:
      - 26379:6379
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mypostgres:
    image: postgres:17.5
    container_name: vergil-postgres
    hostname: vergil-postgres
    user: root
    privileged: true
    ports:
      - 25432:5432
    environment:
      POSTGRES_PASSWORD: xyfs2023
      POSTGRES_USER: postgres
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    volumes:
      - /mnt/data/vergil/postgres:/var/lib/postgresql/data
    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: 4
#          memory: 8G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  myrabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: vergil-rabbitmq
    ports:
      - 25672:5672
      - 35672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=xyfs2023
      - RABBITMQ_DEFAULT_USER=vergil
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mymysql:
    build:
      context: mysql/
      dockerfile: mysql.dockerfile
    container_name: vergil-mysql
    environment:
      MYSQL_ROOT_PASSWORD: xyfs2023 #root管理员用户密码
      MYSQL_DATABASE: nacos_dev
      MYSQL_USER: nacosvergil
      MYSQL_PASSWORD: nacosxyfs2023
      LANG: C.UTF-8
    volumes:
      #mysql数据库挂载到host物理机目录
      - /mnt/data/vergil/mysql/db:/var/lib/mysql
      #容器的配置目录挂载到host物理机目录
      - /mnt/data/vergil/mysql/config:/etc/mysql/conf.d
    ports:
      - 23306:3306
    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: 4
#          memory: 8G
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#  elasticsearch:
#    image: elasticsearch:8.17.1
#    container_name: elasticsearch
#    privileged: true
#    ports:
#      - 29200:9200
#      - 29300:9300
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=true
#      - xpack.license.self_generated.type=basic
#      - xpack.security.http.ssl.enabled=false
#      - xpack.security.transport.ssl.enabled=false
#      - xpack.security.audit.enabled=true
#      - ingest.geoip.downloader.enabled=false
#      - KIBANA_PASSWORD=xyfs2025
#      - ELASTIC_PASSWORD=xyfs2025
#    volumes:
#      - /mnt/data/vergil/es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - /mnt/data/vergil/es/data:/usr/share/elasticsearch/data #数据文件挂载
#      - /mnt/data/vergil/es/config:/usr/share/elasticsearch/config #配置文件挂载
#      - /etc/localtime:/etc/localtime:ro #时间同步
#    networks:
#      - elastic
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
#  kibana:
#    depends_on:
#      - elasticsearch
#    image: kibana:8.17.1
#    container_name: kibana
#    privileged: true
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - I18N_LOCALE="zh-CN"
#      - KIBANA_SYSTEM_PASSWORD=xyfs2025
#      - ELASTICSEARCH_PASSWORD=xyfs2025
#      - ELASTICSEARCH_USERNAME=kibana_system
#    networks:
#      - elastic
#    ports:
#      - 25601:5601
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    privileged: true
    container_name: myminio
    ports:
      - 29000:9000
      - 29090:9090
    command: minio server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=vergil
      - MINIO_ROOT_PASSWORD=xyfs2023
    volumes:
      - /mnt/data/vergil/minio:/data
#    deploy:
#      resources:
#        limits:
#          cpus: 4
#          memory: 8G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mynacos:
    image: nacos/nacos-server:v3.0.1
    container_name: mynacos
    ports:
      - 28080:8080
      - 28848:8848
      - 29848:9848
    volumes:
      - /mnt/data/vergil/nacos:/home/nacos/logs
    env_file:
      - nacos/nacos.env
    depends_on:
      mymysql:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#  sentinel:
#    build:
#      context: sentinel/
#      dockerfile: sentinel.dockerfile
#    image: mysentinel
#    container_name: mysentinel
#    ports:
#      - "8090:8090"
#      - "8719:8719"
#    restart: unless-stopped

#  myseata:
#    image: seataio/seata-server:2.0.0.jre17
#    ports:
#      - "7091:7091"
#      - "8091:8091"
#    environment:
#      - STORE_MODE=db
#      - SEATA_IP=113.141.90.115
#      - SEATA_PORT=8091
#      - TZ=Asia/Shanghai

  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.21
    hostname: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/data/vergil/etcd:/etcd-data
    command: /usr/local/bin/etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir=/etcd-data
    ports:
      - 22379:2379
      - 22380:2380
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mymilvus:
    build:
      context: milvus/
      dockerfile: milvus.dockerfile
    #    image: milvusdb/milvus:v2.5.12
    container_name: milvus-standalone
    hostname: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    security_opt:
      - seccomp:unconfined
    volumes:
      - /mnt/data/vergil/milvus:/var/lib/milvus
    ports:
      - "39530:19530"
      - "39091:9091"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - "minio"
      - "etcd"

  attu:
    container_name: attu
    image: zilliz/attu:v2.5.12
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "33000:3000"
    depends_on:
      - "mymilvus"

#  palu:
#    container_name: mypalu
#    image: jammsen/palworld-dedicated-server:latest
#    restart: unless-stopped
#    logging:
#      driver: "local"
#      options:
#        max-size: "10m"
#        max-file: "3"
#    ports:
#      - target: 8211 # 容器内游戏端口
#        published: 28211 # 宿主机映射端口
#        protocol: udp
#        mode: host
#      - target: 8212 # Gameserver API port inside of the container
#        published: 28212 # Gameserver API port on your host
#        protocol: tcp
#        mode: host
#      - target: 25575 # RCON 容器内
#        published: 25575 # RCON 宿主机映射端口
#        protocol: tcp
#        mode: host
#    volumes:
#      - /mnt/data/palu:/palworld # volume自己去指定
#    env_file:
#      - palu/palword.env

#  rcon:
#    image: outdead/rcon:latest
#    entrypoint: ["/rcon", "-a", "113.141.90.115:25575", "-p", "xyfs2023"]
#    profiles: ["rcon"]

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    ports:
      - 29100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - monitor
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: promethues
    restart: unless-stopped
    user: root
    ports:
      - 29091:9090
    volumes:
      - type: bind
        source: /mnt/data/monitor/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - /mnt/data/monitor/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    # 监控docker用， https://docs.docker.com/config/daemon/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitor
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: root
    volumes:
      - /mnt/data/monitor/grafana:/var/lib/grafana
    ports:
      - "23000:3000"
    networks:
      - monitor
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  ollama:
    image: ollama/ollama:0.9.0
    container_name: ollama
    hostname: ollama
    restart: unless-stopped
    user: root
    volumes:
      - /mnt/data/vergil/ollama:/root/.ollama
    devices:
      - /dev/kfd
      - /dev/dri
    ports:
      - 31434:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.13
    container_name: open-webui
    hostname: open-webui
    volumes:
      - /mnt/data/vergil/openwebui:/app/backend/data
    ports:
      - 28081:8081
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ADMIN_EMAIL=yjb387759719@outlook.com
      - ENABLE_REALTIME_CHAT_SAVE=True
      - HF_ENDPOINT=https://hf-mirror.com
      - PORT=8081
      - DATABASE_URL=postgresql://ollama:ollama@vergil-postgres:5432/webui
      - DATABASE_POOL_SIZE=16
      - JWT_EXPIRES_IN=30d
      - ENABLE_COMMUNITY_SHARING=False
      - VECTOR_DB=milvus
      - MILVUS_URI=http://root:Milvus@milvus-standalone:19530/openwebui
      - MILVUS_DB=openwebui
      - STORAGE_PROVIDER=s3
      - S3_ACCESS_KEY_ID=InV5AW7gpmyrr8IhCF02
      - S3_ADDRESSING_STYLE=path
      - S3_BUCKET_NAME=openwebui
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_KEY_PREFIX=baseService
      - S3_REGION_NAME=cn-northwest-1
      - S3_SECRET_ACCESS_KEY=Fzykpr5SZv84ZzVw8s0CE46RbJer2taOCDLzeuzl
      - REDIS_URL=redis://:xyfs2023@vergil-redis:6379/1
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
      - myredis
      - mypostgres
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  #  mcpo:
  #    image: ghcr.io/open-webui/mcpo:main
  #    container_name: mcpo
  #    ports:
  #      - 28000:8000
  #    #    command: uvx mcpo --port 8000 -- uvx mcp-server-time --local-timezone=Asia/Shanghai
  #    command: uvx mcpo --port 8000 --config /app/config/config.json
  #    volumes:
  #      - /mnt/data/vergil/mcpo/config:/app/config
  #    depends_on:
  #      - open-webui
  #    logging:
  #      options:
  #        max-size: "10m"
  #        max-file: "3"

  # 给大模型用的私有搜索引擎,部署失败
#  searxng:
#    build:
#      context: searxng
#      dockerfile: searxng.dockerfile
#    container_name: searxng
##    image: docker.io/searxng/searxng:latest
#    restart: unless-stopped
#    hostname: searxng
#    ports:
#      - "28080:8080"
#    volumes:
#      - /mnt/data/vergil/searxng:/etc/searxng:rw
#    environment:
#      - SEARXNG_BASE_URL=localhost:8080
#      - SEARXNG_REDIS_URL=redis://:xyfs2023@vergil-redis:6379/1
#    cap_drop:
#      - ALL
#    cap_add:
#      - CHOWN
#      - SETGID
#      - SETUID
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1m"
#        max-file: "1"

#  这个太占内存了，权限管理不行，不太实用
#  windows:
#    image: dockurr/windows
#    container_name: windows
#    environment:
#      VERSION: "win11"
#      DISK_SIZE: "256G"
#      RAM_SIZE: "16G"
#      CPU_CORES: "6"
#      USERNAME: "vergil"
#      PASSWORD: "921115"
#    devices:
#      - /dev/kvm
#    cap_add:
#      - NET_ADMIN
#    volumes:
#      - /mnt/data/windows:/storage
#      - /mnt/data/shared:/shared
#    ports:
#      - 28006:8006
#      - 23389:3389/tcp
#      - 23389:3389/udp
#    stop_grace_period: 2m
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"

  mygitlab:
    image: gitlab/gitlab-ce:18.0.1-ce.0
    container_name: gitlab
    user: root
#    restart: always
    hostname: 223.72.5.245
    ports:
      - '20080:80'
      - '20443:443'
      - '20222:22'
    environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          registry_external_url 'http://223.72.5.245:20080'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['initial_root_password'] = 'xyfs2023'
          postgresql['enable'] = false 
          gitlab_rails['db_adapter'] = 'postgresql'
          gitlab_rails['db_encoding'] = 'utf8'
          gitlab_rails['db_host'] = 'vergil-postgres'
          gitlab_rails['db_port'] = 5432
          gitlab_rails['db_username'] = 'gitlab'
          gitlab_rails['db_password'] = 'xyfs2023'
          gitlab_rails['gitlab_email_from'] = 'yjb387759719@outlook.com'
          gitlab_rails['gitlab_email_reply_to'] = 'yjb387759719@outlook.com'
          gitlab_rails['microsoft_graph_mailer_enabled'] = false
          logging['logrotate_frequency'] = "daily"
          logging['logrotate_rotate'] = 30
          logging['logrotate_compress'] = "compress"
          logging['logrotate_method'] = "copytruncate"
          redis['enable'] = false
          gitlab_rails['redis_host'] = 'vergil-redis'
          gitlab_rails['redis_port'] = 6379
          gitlab_rails['redis_password'] = 'xyfs2023'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp-mail.outlook.com"
          gitlab_rails['smtp_port'] = 587
          gitlab_rails['smtp_user_name'] = "yjb387759719@outlook.com"
          gitlab_rails['smtp_password'] = "19921115ctzL!"
          gitlab_rails['smtp_domain'] = "smtp-mail.outlook.com"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
          gitlab_shell['log_format'] = 'text'
          gitlab_workhorse['log_format'] = 'text'
          registry['log_formatter'] = 'text'
          sidekiq['log_format'] = 'text'
          gitlab_pages['log_format'] = 'text'
          registry['log_level'] = 'info'
          gitlab_shell['log_level'] = 'INFO'
          prometheus['enable'] = false
          gitlab_exporter['enable'] = false
          prometheus_monitoring['enable'] = false
          sidekiq['metrics_enabled'] = false
          puma['exporter_enabled'] = false
          nginx['enable'] = false
          gitlab_workhorse['listen_network'] = "tcp"
          gitlab_workhorse['listen_addr'] = "0.0.0.0:80"
    volumes:
      - /mnt/data/vergil/gitlab:/etc/gitlab
      - /mnt/data/vergil/gitlab:/var/log/gitlab
      - /mnt/data/vergil/gitlab:/var/opt/gitlab
    depends_on:
      - mypostgres
      - myredis
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  #智能爬虫，目前给dify用，已集成MCP
  crawl4ai:
    image: unclecode/crawl4ai:0.6.0-r2
    ports:
      - "11235:11235"  # Gunicorn port
    volumes:
      - /mnt/data/vergil/ollama/crawl4ai/dev/shm:/dev/shm  # Chromium performance
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11235/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

# 下面是dify
  dify-api:
    image: langgenius/dify-api:1.4.1
    hostname: api
#    restart: always
    environment:
      # Startup mode, 'api' starts the API server.
      MODE: api
    depends_on:
      - mypostgres
      - myredis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - /mnt/data/vergil/dify/storage:/app/api/storage
    ports:
      - 25001:5001
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - dify/dify.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  dify-worker:
    image: langgenius/dify-api:1.4.1
    hostname: worker
#    restart: always
    environment:
      # Startup mode, 'worker' starts the Celery worker for processing the queue.
      MODE: worker
    depends_on:
      - mypostgres
      - myredis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - /mnt/data/vergil/dify/storage:/app/api/storage
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - dify/dify.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  dify-web:
    image: langgenius/dify-web:1.4.1
    hostname: web
    extra_hosts:
      - host.docker.internal:host-gateway
#    restart: always
    env_file:
      - dify/dify.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  sandbox:
    image: langgenius/dify-sandbox:0.2.12
    #    restart: always
    environment:
      # The DifySandbox configurations
      # Make sure you are changing this key for your deployment with a strong key.
      # You can generate a strong key using `openssl rand -base64 42`.
      API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      GIN_MODE: ${SANDBOX_GIN_MODE:-release}
      WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
      ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
      HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
      HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
      SANDBOX_PORT: 8194
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
    volumes:
      - /mnt/data/vergil/dify/sandbox/dependencies:/dependencies
      - /mnt/data/vergil/dify/sandbox/conf:/conf
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8194/health' ]
    extra_hosts:
      - host.docker.internal:host-gateway

  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.1.1-local
    restart: always
    environment:
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
      PLUGIN_STORAGE_TYPE: ${PLUGIN_STORAGE_TYPE:-local}
      PLUGIN_STORAGE_LOCAL_ROOT: ${PLUGIN_STORAGE_LOCAL_ROOT:-/app/storage}
      PLUGIN_INSTALLED_PATH: ${PLUGIN_INSTALLED_PATH:-plugin}
      PLUGIN_PACKAGE_CACHE_PATH: ${PLUGIN_PACKAGE_CACHE_PATH:-plugin_packages}
      PLUGIN_MEDIA_CACHE_PATH: ${PLUGIN_MEDIA_CACHE_PATH:-assets}
    env_file:
      - dify/dify.env
    ports:
      - 5003:5003
    volumes:
      - /mnt/data/vergil/dify/plugin_daemon/storage:/app/storage

  # The nginx reverse proxy.
  # used for reverse proxying the API service and Web service.
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /mnt/data/vergil/dify/nginx:/etc/nginx
      - type: bind
        source: /mnt/data/vergil/dify/nginx/docker-entrypoint.sh
        target: /docker-entrypoint-mount.sh
        read_only: true
    entrypoint:
      [
        'sh',
        '-c',
        "cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/\r$$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh",
      ]
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-_}
      NGINX_HTTPS_ENABLED: ${NGINX_HTTPS_ENABLED:-false}
      NGINX_SSL_PORT: ${NGINX_SSL_PORT:-443}
      NGINX_PORT: ${NGINX_PORT:-80}
      NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES:-4}
      NGINX_KEEPALIVE_TIMEOUT: ${NGINX_KEEPALIVE_TIMEOUT:-65}
      NGINX_PROXY_READ_TIMEOUT: ${NGINX_PROXY_READ_TIMEOUT:-3600s}
      NGINX_PROXY_SEND_TIMEOUT: ${NGINX_PROXY_SEND_TIMEOUT:-3600s}
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE:-300M}
    depends_on:
      - dify-api
      - dify-web
    ports:
      - "30080:80"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#  radicale:
#    image: tomsquest/docker-radicale:3.3.1.0
#    init: true
#    read_only: true
#    security_opt:
#      - no-new-privileges:true
#    cap_drop:
#      - ALL
#    cap_add:
#      - SETUID
#      - SETGID
#      - CHOWN
#      - KILL
#    healthcheck:
#      test: curl -f http://127.0.0.1:5232 || exit 1
#      interval: 30s
#      retries: 3
#    restart: unless-stopped
#    ports:
#      - 25232:5232
#    volumes:
#      - /mnt/data/wangjs35/radicale/data:/data
#      - /mnt/data/wangjs35/radicale/config:/config:ro

#  mcsweb:
#    image: githubyumao/mcsmanager-web:latest
#    ports:
#      - "23333:23333"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/data/vergil/mcsmanage/web/data:/opt/mcsmanager/web/data
#      - /mnt/data/vergil/mcsmanage/web/logs:/opt/mcsmanager/web/logs
#
#  mcsdaemon:
#    image: githubyumao/mcsmanager-daemon:latest
#    restart: unless-stopped
#    ports:
#      - "24444:24444"
#    environment:
#      - MCSM_DOCKER_WORKSPACE_PATH=/mnt/data/vergil/mcsmanage/daemon/data/InstanceData
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /mnt/data/vergil/mcsmanage/daemon/data:/opt/mcsmanager/daemon/data
#      - /mnt/data/vergil/mcsmanage/daemon/logs:/opt/mcsmanager/daemon/logs
#      - /var/run/docker.sock:/var/run/docker.sock

#  rimworld:
#    image: dalcop/rimworld-together:25.1.2.1
#    restart: unless-stopped
#    ports:
#      - 25555:25555
#    volumes:
#      - /mnt/data/wangyb80/rimworld:/Data