version: "3"

services:
  myredis:
    build:
      context: redis/
      dockerfile: redis.dockerfile
    container_name: vergil-redis
    ports:
      - 6379:6379
    restart: always
#  myredis2:
#    build:
#      context: redis/
#      dockerfile: redis.dockerfile
#    container_name: myredis2
#    ports:
#      - 6380:6379
#    restart: always
  mypostgres:
    image: postgres:16beta1-alpine
    container_name: vergil-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 921115
      POSTGRES_USER: postgres
    volumes:
      - /mnt/data/vergil/postgres:/var/lib/postgresql/data
    restart: always
#  mypostgres2:
#    build:
#      context: postgresql/
#      dockerfile: postgre2.dockerfile
#    container_name: mypostgres2
#    ports:
#      - 5433:5432
#    restart: always
  myrabbitmq:
    image: rabbitmq:management-alpine
    container_name: vergil-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=921115
      - RABBITMQ_DEFAULT_USER=vergil
    restart: always
  mymysql:
    image: mysql:8.0.33
    container_name: vergil-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_USER: vergil   #创建test用户
      MYSQL_PASSWORD: 921115  #设置test用户的密码
    volumes:
      #mysql数据库挂载到host物理机目录
      - /mnt/data/vergil/mysql/db:/var/lib/mysql
      #容器的配置目录挂载到host物理机目录
      - /mnt/data/vergil/mysql/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: always
#  myelasticsearch:
#    image: elasticsearch:8.6.1
#    container_name: myelasticsearch
#    networks:
#      - ek-net
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      - "discovery.type=single-node"
#      - xpack.security.enabled=false  #没这玩意kibana就是跑不起来
#    volumes:
#      - /root/es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - /root/es/data:/usr/share/elasticsearch/data #数据文件挂载
#  mykibana:
#    depends_on:
#      - myelasticsearch
#    image: kibana:8.6.1
#    container_name: mykibana
#    networks:
#      - ek-net
#    environment:
#      - ELASTICSEARCH_HOSTS=http://myelasticsearch:9200
#      - I18N_LOCALE="zh-CN"
#    ports:
#      - 5601:5601
#networks:
#  ek-net:
#    driver: bridge
#  mynacos:
#    image: nacos/nacos-server:v2.2.3-slim
#    container_name: mynacos
#    ports:
#      - 8848:8848
#      - 9848:9848
#    environment:
#      - NACOS_AUTH_IDENTITY_KEY=123456
#      - NACOS_AUTH_IDENTITY_VALUE=123456
#      - NACOS_AUTH_TOKEN=MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5MTIzNDU2Nzg5
#      - MODE=standalone
#  myminio:
#    image: minio/minio:RELEASE.2023-04-13T03-08-07Z
#    privileged: true
#    container_name: myminio
#    ports:
#      - 9000:9000
#      - 9001:9001
#    command: server /data --console-address ":9001"
#    environment:
#      - MINIO_ROOT_USER=admin
#      - MINIO_ROOT_PASSWORD=12345678
