global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "vergil-lab-monitor"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      # 容器内部通信不能用宿主机映射端口，域名用服务名
      - targets: ['node_exporter:9100']

#  - job_name: docker
#    # metrics_path defaults to '/metrics'
#    # scheme defaults to 'http'.
#    # 没有现成的grafana面板，只收集数据，不做可视化
#    static_configs:
#      - targets: [ "host.docker.internal:9323" ]

#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080

#本地grafana,没用云
#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'